module.exports.admins = require('./admins')
module.exports.hunters = require('./hunters')
module.exports.organizations = require('./organizations')
module.exports.failures = require('./failures')
module.exports.publics = require('./publics')
